config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :users

  resources :users do
    get '/all_adoptions', to: "profiles#all_adoptions", as: :all_adoptions
    get '/adoption_show', to: "profiles#adoption_show", as: :adoption_show
    # get '/adoption_show/edit_confirm_adoption', to: "profiles#confirm_adoption_edit", as: :confirm_adoption_edit
    post '/adoption_confirm/:id', to: "profiles#adoption_confirm", as: :adoption_confirm
    post '/adoption_refuse/:id', to: "profiles#adoption_refuse", as: :adoption_refuse

  end

  resources :pets do
    resources :adoptions, only: [:new, :create]
  end

  resource :profiles, only: [:show]

  post '/request_reply/:id', to: 'profiles#reply_request', as: :reply

end

app/models/adoption.rb
class Adoption < ApplicationRecord
  belongs_to :user
  belongs_to :pet

  validates :content, presence: true
  validates :status, inclusion: { in: %w(open confirmed refused),
    message: "%{value} is not a valid status" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :adoptions

  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :adoptions
  has_many :pets
  has_one_attached :photo

  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController
  def new
    @pet = Pet.find(params[:pet_id])
    @adoption = Adoption.new
  end

  def create
    @adoption = Adoption.new(adoption_params)
    @adoption.user = current_user
    @adoption.pet = Pet.find(params[:pet_id])
    if @adoption.save
      mail = UserMailer.with(pet: @adoption.pet, adoption: @adoption).adoption
      mail.deliver_now
      redirect_to pet_path(@adoption.pet), notice: "Adoption created, message sent"
    else
      render :new
    end
  end

  private

  def adoption_params
    params.require(:adoption).permit(:pet_id, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

       def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :date_of_birth, :doc_cpf, :description, :address, :photo, :email, :password)}

            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :date_of_birth, :doc_cpf, :description, :address, :photo, :email, :password, :current_password)}
       end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @pets = Pet.all
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pets_params)
    @pet.user = current_user

    if @pet.save
      unless @pet.photo.attached?
        @pet.photo.attach(io: open('app/assets/images/default pet photo.jpg'), filename: 'nes.png', content_type: 'image/jpg')
      end
      redirect_to pet_path(@pet.id)
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pets_params)

    if @pet.save
      redirect_to pet_path(@pet.id)
    else
      render :edit
    end
  end

  def pets_params
    params.require(:pet).permit(:animal_type, :name, :age, :description, :photo)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_adoption_requests, only: %i[show]

  def show
    @user = current_user
  end

  def all_adoptions
    @user = User.find(params[:user_id])
  end

  def adoption_show
    @adoption = Adoption.find(params[:user_id])
  end

  def reply_request
    @adoption = Adoption.find(params[:id])
    @message = params[:reply_message]
    mail = UserMailer.with(message: @message, adoption: @adoption).reply
    mail.deliver_now
    render :adoption_show, notice: "reply sent"
  end

  def adoption_confirm
    @adoption = Adoption.find(params[:id])
    @adoption.status = 'confirmed'
    @adoption.concluded = 'true'
    @adoption.concluded_at = Date.today
    if @adoption.save
      redirect_to profiles_path, notice: "adoption confirmed, transaction concluded"
    else
      render :adoption_show, notice: "adoption couldn`t be confirmed, please try again"
    end
  end

  def adoption_refuse
    @adoption = Adoption.find(params[:id])
    @adoption.status = 'refused'
    @adoption.concluded = 'true'
    @adoption.concluded_at = Date.today
    if @adoption.save
      redirect_to profiles_path, notice: "adoption refused, transaction concluded"
    else
      render :adoption_show, notice: "adoption couldn`t be refused, please try again"
    end
  end

  private

  def set_adoption_requests
    pets = current_user.pets
    @pets_adoptions = pets.map do |pet|
      Adoption.where("pet_id = ? AND status = ?", pet[:id], 'open')
    end
  end

  def adoption_params
    params.require(:adoption).permit(:id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show update destroy]
  before_action :spot_user, only: %i[edit]

  def index
    @users = User.all.shuffle
  end

  def show
    @user = User.find(params[:id])
  end

  # device funcionality (new and create)

  def edit
    @user = spot_user
  end

  def update
    @user.update(user_params)
    if @users.save
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def set_user
    @user = current_user
  end

  def spot_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:description, :address)
  end
end

app/helpers/adoptions_helper.rb
module AdoptionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/adoptions/all_adoptions.html.erb
<h1> <%= "All adoptions by #{@user.name}:" %></h1>
<%= button_to "back", user_path(@user), method: :get, class: "btn btn-primary" %>
<% if @all_adoptions.empty? %>
  <p><%= "There have been no prior adoptions by #{@user.name.}" %></p>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">pet name</th>
        <th scope="col">adopted by</th>
        <th scope="col">adoption date</th>
      </tr>
    </thead>
    <tbody>
      <% @all_adoptions.each do |adoption| %>
        <% if adoption.concluded? %>
          <tr>
          <td><%= adoption.pet.name %></td>
          <td><%= adoption.pet.user_id %></td>
          <td><%= adoption.concluded_at %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/adoptions/new.html.erb
  <%= simple_form_for [@pet, @adoption], url: pet_adoptions_path do |f| %>
    <%= f.input :content, as: :text %>
    <%= f.submit "Solicitar adoção", class: "btn btn-success" %>
  <% end %>

app/views/home/index.html.erb
<div class="container mt-3" >
    <div class="container mt-3" >
    <div class="banner"
      style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/3628100/pexels-photo-3628100.jpeg?cs=srgb&dl=pexels-eddie-galaxy-3628100.jpg&fm=jpg);">
      <div class="container">
        <p class="text-right"> Help thousands of pets find a new home</p>
        <p class="text-right">
          <span id="banner-typed-text"></span>
        </p>
        <p id="btnbanner" class="text-center">
        <% unless user_signed_in?  %>
          <%= link_to "Join this community today", new_user_registration_path, class: "btn btn-success"  %>
        <% end  %>
        </p>
      </div>
    </div>
  </div>
  <div class="container mt-5">
    <div class="cards">
      <% @pets.each do |pet| %>
        <a href="<%= " /pets/#{pet.id}" %>">
          <div class="card-category"
            style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path pet.photo.key, height: 300, crop: :fill if pet.photo.attached? %>')">
            <%= pet.name %>
          </div>
        </a>
        <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Rails Pets Marketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="page-container">
    <div id="content-wrap">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class = container>
    <%= yield %>
    </div>
    <div class="container">
    <div id="footer">
    <%= render 'shared/footer' %>
    </div>
    </div>
    </div>
    </div>
  </body>
</html>

app/views/pets/edit.html.erb
<div class="container-fluid my-5">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
            <div class="card p-3">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <h2 class="heading text-center center" style="color: rgb(40,40,40);">edit pet profile:</h2>
                    </div>
                </div>
                <%= simple_form_for(@pet) do |f| %>
                    <%= f.input :animal_type %>
                        <%= f.input :name %>
                            <%= f.input :age %>
                                <%= f.input :description %>
                                    <%= f.input :photo, as: :file %>
                                        <%= f.submit "Edite meu pet", class: "btn btn-success" %>
                                            <% end %>
            </div>
        </div>
    </div>
</div>

app/views/pets/new.html.erb
<div class="container-fluid my-5">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8">
      <div class="card p-3">
        <div class="row justify-content-center">
          <div class="col-12">
            <h2 class="heading text-center">Do have a pet to donate?</h2>
            <h4 class="heading text-center"><strong>You're in the right place</strong></h4>
          </div>
        </div>
        <%= simple_form_for(@pet) do |f| %> <%= f.input :animal_type %>
          <%=f.input :name %>
          <%= f.input :age %>
          <%= f.input :description %>
          <%= f.input :photo, as: :file %>
          <div style="display: flex; justify-content: space-between;">
            <a class="btn btn-success mx-2" onclick="history.back(-1)">I've changed my mind!</a>
            <%=f.submit "Find my pet an owner!", class: "btn btn-success mx-2", style: "width: auto;"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pets/show.html.erb
<div class="container-fluid my-5">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8">
      <div class="card p-3">
        <div class="row justify-content-center">
          <div class="col-12">
            <h1 class="heading text-center">Hello, I`m: <%= @pet.name.capitalize %>!</h1>

            <div class="container d-flex justify-content-center">
              <%= image_tag "#{@pet.photo.attached? ? "#{cl_image_path @pet.photo.key, crop: :fill}" : 'default pet photo.jpg'}", class: "avatar-very-large-bordered m-2" %>
            </div>
            <p></p>
            <h5>about <%= @pet.name.capitalize %>:</h5>

            <ul class="list-group">
              <li class="list-group-item">type: <%= @pet.animal_type %></li>
              <li class="list-group-item">owner: <%= @pet.user.first_name%></li>
              <li class="list-group-item">age: <%= @pet.age %></li>
              <li class="list-group-item">more: <%= @pet.description %></li>
            </ul>

            <div style="display: flex; justify-content: space-evenly; align-items: center;">
              <%= link_to "adopt", new_pet_adoption_path(pet_id: @pet.id), class: "btn btn-success", style: "width: 100px; margin: 15px;" %>
              <%= link_to "back", root_path, class: "btn btn-success", style: "width: 100px; margin: 15px;" %>
              <%= link_to "edit", edit_pet_path(@pet.id), class: "btn btn-success", style: "width: 100px; margin: 15px;" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/adoption_show.html.erb
<div class="container mt-2>
  <% if @adoption.user.first_name != nil  %>
    <h4>Adoption request by <%= @adoption.user.first_name %></h4>
  <% else %>
    <h4>Adoption request by <%= @adoption.user.email %>"</h4>
  <% end %>

  <ul class="list-group">
    <li class="list-group-item">Pet name: <%= @adoption.pet.name  %></li>
    <li class="list-group-item">Request initiated by: <%= @adoption.user.first_name %> <%= @adoption.user.first_name %></li>
    <li class="list-group-item">e-mail: <%= @adoption.user.email %></li>
    <li class="list-group-item">Date of request: <%= @adoption.created_at %></li>
    <li class="list-group-item">Message: <%@adoption.content%></li>
  </ul>
</div>
<div class="container mt-2">
  <div class="container_adoption_show">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" style="width: 180px;">reply</button>
    <%= link_to user_adoption_confirm_path(id: @adoption.id), method: :post do %>
      <div class="btn btn-success", style="width: 180px">confirm adoption</div>
    <% end %>
    <%= link_to user_adoption_refuse_path(id: @adoption.id), method: :post do %>
      <div class="btn btn-danger", style="width: 180px">refuse adoption</div>
    <% end %>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">reply to adoption request</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_tag reply_path(@adoption), method: :post do %>
        <div class="modal-body">
          <div class="input-group">
            <textarea class="form-control" name="reply_message" aria-label="With textarea"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <input type="submit" class="btn btn-success" value="send message">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/all_adoptions.html.erb
<div class="container mt-3">
  <h4> <%= "All pets offered for adoption by #{@user.first_name} #{@user.last_name}:" %></h4>
  <p></p>
  <p></p>
  <% if @user.adoptions.empty? %>
    <p><%= "There have been no prior adoptions by #{@user.email}" %></p>
  <% else %>
    <table class="table">
      <thead class="bg-success">
        <tr>
          <th scope="col">pet name:</th>
          <th scope="col">pet type:</th>
          <th scope="col">adoption offered on:</th>
          <th scope="col">adoption requested by:</th>
          <th scope="col">adoption status:</th>
          <th scope="col">adoption date:</th>
        </tr>
      </thead>
      <tbody>
        <% @user.adoptions.each do |adoption| %>
          <% if adoption.concluded? %>
            <tr>
            <td><%= adoption.pet.name %></td>
            <td><%= adoption.pet.animal_type %></td>
            <td><%= adoption.created_at %></td>
            <td><%= adoption.user.first_name %></td>
            <td><%= adoption.status %></td>
            <td><%= adoption.concluded_at %></td>
            </tr>
          <% end %>
          <!-- <p></p> -->
        <% end %>
      </tbody>
    </table>
  <% end %>
  <p></p>
  <p></p>
  <%= button_to "back", user_path(@user), method: :get, class: "btn btn-success", style: "width: 160px;"%>
</div>

app/views/profiles/show.html.erb
<div class="container text center" style="background-image: url(https://placedog.net/640/480?random); background-size: cover;">
  <div class="container col-2 d-flex justify-content-center align-items-center flex-column">
    <%= image_tag "#{current_user.photo.attached? ? "#{cl_image_path current_user.photo.key, crop: :fill}" : 'https://source.unsplash.com/eRDnW-NzbKc/1600x900'}", class: "avatar-very-large-bordered m-2" %>
    <div class="d-flex justify-content-space-around">
      <a class="btn btn-success m-3" href="/users/edit" style="width: 100px">edit profile</a>
      <a class="btn btn-success m-3" href="/" style="width: 100px">adopt a pet</a>
      <a class="btn btn-success m-3" href="/pets/new" style="width: 100px">donate a pet</a>
      <a class="btn btn-success m-3" href=<%="/users/#{current_user.id}/all_adoptions"%> style="width: 100px">user history</a>
    </div>
  </div>
</div>

<hr>

<div class="border border-dark rounded my-4 shadow">
  <h2 class="m-3 text-center">About <%= current_user.first_name.capitalize %></h2>
  <hr>
  <ul>
    <li><p class="m-3"><strong>First name: </strong><%=current_user.first_name%></p></li>
    <li><p class="m-3"><strong>Last name: </strong><%=current_user.last_name%></p></li>
    <li><p class="m-3"><strong>Date of birth: </strong><%=current_user.date_of_birth%></p></li>
    <li><p class="m-3"><strong>Address: </strong><%=current_user.address%></p></li>
    <li><p class="m-3"><strong>Email: </strong><%=current_user.email%></p></li>
    <li><p class="m-3"><strong>User description: </strong><%=current_user.description%></p></li>
  </ul>
</div>
<hr class="m-3">
  <div class="border border-dark rounded my-4 shadow">
      <div class="container" style="mt-3">
          <h4 class="m-3 text-center">pending adoption requests</h4>
          <table class="table">
            <% if @pets_adoptions.empty? %>
              <p style="text-align: center">--currently, there are no pending adoption requests for <%= current_user.first_name.capitalize %>--</p>
            <% else %>
              <p style="text-align: center; color: red; font-weight: bolder;"><strong>--You received an adoption resquest!--</strong></p>
              <thead>
                <tr>
                  <th scope="col">pet name</th>
                  <th scope="col">requested by</th>
                  <th scope="col">e-mail</th>
                  <th scope="col">message</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                <% @pets_adoptions.each do |pet_adoption| %>
                  <% pet_adoption.each do |adoption| %>
                    <tr>
                      <td><%= adoption.pet.name %></td>
                      <td><%= adoption.user.first_name %></td>
                      <td><%= adoption.user.email %></td>
                      <td><%= adoption.content %></td>
                      <td><%= link_to "check request", user_adoption_show_path(user_id: adoption.id), method: :get %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
    <% end %>
  </div>

<div class="border border-dark rounded my-4 shadow">
  <h4 class="m-3 text-center">pets offered by <%= current_user.first_name.capitalize %></h2>
  <hr>
  <% if @user.pets.empty? %>
    <p style="text-align: center">--currently, no pets are in offer by <%= current_user.first_name.capitalize %>--</p>
  <% else %>
  <div class="container my-3">
    <div class="cards">
      <% @user.pets.each do |pet| %>
        <a href="<%= " /pets/#{pet.id}" %>">
          <div class="card-category"
            style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path pet.photo.key, height: 300, crop: :fill if pet.photo.attached? %>')">
            <%= pet.name %>
          </div>
        </a>
        <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/lcgoliveira/rails-pets-marketplace" target="/blank"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    This footer was made by ForgeHub Team <i class="fas fa-laptop-code"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to "/", class: "navbar-brand" do %>

    <%= image_tag "forrgehubpet.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "#{current_user.photo.attached? ? "#{cl_image_path current_user.photo.key, crop: :fill}" : 'https://source.unsplash.com/eRDnW-NzbKc/1600x900'}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile Page", profiles_path, class: "dropdown-item" %>
            <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Donate a pet", new_pet_path, class: "dropdown-item" %>
            <%= link_to "Adopt a pet", root_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-flat" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>